Repository wp-graphql/wp-graphql-acf, pull requests merged in 2019-10, with the labels that each got.

#66 Adds Options page support.
  .env.dist
  .gitignore
  .travis.yml
  bin/install-wp-tests.sh
  codeception.dist.yml
  codeception.yml
  composer.json
  composer.lock
  src/class-config.php
  tests/functional.suite.dist.yml
  tests/wpunit.suite.dist.yml
  tests/wpunit/PostObjectFieldsTest.php
  wp-graphql-acf.php
Labels: PR: Needs Tests

#75 Release/v0.3.0
  .env.dist
  .gitignore
  .travis.yml
  bin/install-wp-tests.sh
  codeception.dist.yml
  codeception.yml
  composer.json
  composer.lock
  src/class-acf.php
  src/class-config.php
  tests/_data/config.php
  tests/functional.suite.dist.yml
  tests/wpunit.suite.dist.yml
  tests/wpunit/PostObjectFieldsTest.php
  wp-graphql-acf.php
Labels: Breaking Change, Release

#81 Release/v0.3.0
  src/class-acf.php
  src/class-config.php
  tests/_data/config.php
  tests/wpunit/PostObjectFieldsTest.php
  wp-graphql-acf.php
Labels: Release
